#!/usr/bin/env bun
// RenderTodoComment.ts — render typed Todo[] back into a markdown PR comment
// suitable for `gh pr comment {N} --body @-` or `gh pr comment {N} --body-file ...`.
//
// Output shape (deterministic — identical input always produces identical output):
//
//   ## DOS FastAPIStarterTeam review
//
//   **PR:** #42 — fix the thing
//   **Reviewers:** backend, security, qa
//   **Verdict:** {teamVerdict}
//
//   ### TODOs by agent
//
//   #### Backend (3)
//   - [ ] (agent:backend) (priority:high) (file:src/app/api/v1/users.py:12) Move auth check
//   - [x] (agent:backend) (priority:medium) Add input validation
//   - [ ] (agent:backend) (priority:low) Rename helper for clarity
//
//   #### Database (1)
//   - [ ] (agent:database) (priority:high) Add tenant_id index
//
//   ---
//   _Generated by DOS FastAPIStarterTeam. Comment is auto-regenerated each loop. Merges require human approval._
//
// Sibling: MakerkitTeam/Tools/RenderTodoComment.ts. Same shape, FastAPI-flavored
// agent labels (apidx/schema/agent replace ux/ui/frontend).

import type { Todo, AgentId, Priority } from './ParsePrTodos';
import { formatVerdict, type Verdict } from './_shared';

export interface RenderMeta {
  prNumber: number;
  prTitle: string;
  reviewers: readonly AgentId[];
  teamVerdict: Verdict;
}

const PRIORITY_ORDER: Record<Priority, number> = { high: 0, medium: 1, low: 2 };
const AGENT_LABEL: Record<AgentId, string> = {
  pm: 'Product Manager',
  sm: 'Scrum Master',
  apidx: 'API DX',
  schema: 'Schema',
  architect: 'Architect',
  agent: 'Agent Engineer',
  backend: 'Backend',
  database: 'Database',
  security: 'Security',
  qa: 'QA',
  e2e: 'E2E',
  devops: 'DevOps',
  writer: 'Writer',
};

function renderTodoLine(t: Todo): string {
  const mark = t.done ? 'x' : ' ';
  const file = t.file ? ` (file:${t.file})` : '';
  const blocked = t.blocked ? ` <!-- blocked: ${t.blocked} -->` : '';
  return `- [${mark}] (agent:${t.agent}) (priority:${t.priority})${file} ${t.description}${blocked}`;
}

export function renderComment(todos: readonly Todo[], meta: RenderMeta): string {
  const grouped = new Map<AgentId, Todo[]>();
  for (const t of todos) {
    if (!grouped.has(t.agent)) grouped.set(t.agent, []);
    grouped.get(t.agent)!.push(t);
  }
  // Sort each group by priority then by done-state (undone first)
  for (const list of grouped.values()) {
    list.sort((a, b) => {
      if (a.done !== b.done) return a.done ? 1 : -1;
      return PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority];
    });
  }
  // Order groups: highest count of undone-high first, then alphabetical by agent label
  const groupKeys = [...grouped.keys()].sort((a, b) => {
    const ua = grouped.get(a)!.filter((t) => !t.done && t.priority === 'high').length;
    const ub = grouped.get(b)!.filter((t) => !t.done && t.priority === 'high').length;
    if (ua !== ub) return ub - ua;
    return AGENT_LABEL[a].localeCompare(AGENT_LABEL[b]);
  });

  const sections: string[] = [];
  sections.push('## DOS FastAPIStarterTeam review');
  sections.push('');
  sections.push(`**PR:** #${meta.prNumber} — ${meta.prTitle}`);
  sections.push(`**Reviewers:** ${meta.reviewers.join(', ')}`);
  sections.push(`**Verdict:** ${formatVerdict(meta.teamVerdict)}`);
  sections.push('');
  sections.push('### TODOs by agent');
  sections.push('');

  if (groupKeys.length === 0) {
    sections.push('_No actionable TODOs — all reviewers returned PASS._');
  } else {
    for (const key of groupKeys) {
      const list = grouped.get(key)!;
      sections.push(`#### ${AGENT_LABEL[key]} (${list.length})`);
      for (const t of list) sections.push(renderTodoLine(t));
      sections.push('');
    }
  }

  sections.push('---');
  sections.push('_Generated by DOS FastAPIStarterTeam. Comment is auto-regenerated each loop. Merges require human approval._');
  return sections.join('\n');
}

// CLI entry: read JSON {todos, meta} from stdin, emit markdown.
//   echo '{"todos":[...],"meta":{...}}' | bun RenderTodoComment.ts
if (import.meta.main) {
  const { readStdin } = await import('./_shared');
  const input = await readStdin();
  const payload = JSON.parse(input) as { todos: Todo[]; meta: RenderMeta };
  process.stdout.write(renderComment(payload.todos, payload.meta) + '\n');
}
