/**
 * R100 — tools-lint-wired. Canonical-format campaign Tier C (2026-07-06).
 *
 * The Tools/ authoring standard is EXECUTABLE, not prose (Docs/TOOLING.md
 * carries rationale only): scaffold-tool.ts stamps conforming skeletons,
 * lint-tools.ts checks conventions against a shrink-only grandfather
 * baseline, and tools-catalog.ts generates Tools/README.md from tool
 * headers with a --check drift gate. That stack only works while every
 * piece stays present AND wired into pre-commit + CI — an unwired checker
 * is prose with extra steps (the audit's "existence ≠ enforcement" class).
 *
 * Presence probes (all pure f(HEAD) — committed determinism class):
 *   1. Tools/scaffold-tool.ts exists
 *   2. Tools/lint-tools.ts exists
 *   3. Tools/tools-catalog.ts exists
 *   4. Tools/lint-tools-baseline.json exists and parses (the grandfather ledger)
 *   5. Docs/TOOLING.md exists (the rationale doc the tools cite)
 *   6. Tools/README.md carries the GENERATED-by-tools-catalog marker
 *   7. Tools/hooks/pre-commit wires lint-tools.ts (Gate 23)
 *   8. .github/workflows/release-readiness.yml wires lint-tools.ts --check
 *      AND tools-catalog.ts --check (the gate that cannot be --no-verify'd)
 *
 * Status:
 *   - pass: all 8 probes hit
 *   - fail: any probe misses; evidence names each miss
 *   - not_applicable: Tools/ directory absent (non-DOS repo)
 *
 * Test seam: ctx.repoRoot.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { CheckContext, CheckResult } from "../types.ts";

const REQUIREMENT =
  "The Tools/ authoring stack (scaffold-tool + lint-tools + baseline + tools-catalog + TOOLING.md) MUST exist and stay wired into pre-commit Gate 23 and the release-readiness CI gate";

function fileContains(path: string, needle: string): boolean {
  try {
    return readFileSync(path, "utf8").includes(needle);
  } catch {
    return false;
  }
}

export async function r100ToolsLintWired(ctx: CheckContext): Promise<CheckResult> {
  const root = ctx.repoRoot;
  if (!existsSync(join(root, "Tools"))) {
    return {
      rId: "R100",
      requirement: REQUIREMENT,
      status: "not_applicable",
      evidence: [`Tools/ not found under ${root}`],
    };
  }

  const misses: string[] = [];

  for (const rel of [
    "Tools/scaffold-tool.ts",
    "Tools/lint-tools.ts",
    "Tools/tools-catalog.ts",
    "Docs/TOOLING.md",
  ]) {
    if (!existsSync(join(root, rel))) misses.push(`${rel}: absent`);
  }

  const baselinePath = join(root, "Tools", "lint-tools-baseline.json");
  if (!existsSync(baselinePath)) {
    misses.push("Tools/lint-tools-baseline.json: absent (the grandfather ledger)");
  } else {
    try {
      const b = JSON.parse(readFileSync(baselinePath, "utf8")) as { violations?: unknown };
      if (typeof b.violations !== "object" || b.violations === null) {
        misses.push("Tools/lint-tools-baseline.json: parses but has no violations map");
      }
    } catch {
      misses.push("Tools/lint-tools-baseline.json: unparseable JSON");
    }
  }

  if (!fileContains(join(root, "Tools", "README.md"), "GENERATED by Tools/tools-catalog.ts")) {
    misses.push("Tools/README.md: missing the GENERATED-by-tools-catalog marker (hand-written README regressed?)");
  }
  if (!fileContains(join(root, "Tools", "hooks", "pre-commit"), "lint-tools.ts")) {
    misses.push("Tools/hooks/pre-commit: Gate 23 unwired (no lint-tools.ts reference)");
  }
  const ci = join(root, ".github", "workflows", "release-readiness.yml");
  if (!fileContains(ci, "lint-tools.ts --check")) {
    misses.push("release-readiness.yml: lint-tools --check unwired");
  }
  if (!fileContains(ci, "tools-catalog.ts --check")) {
    misses.push("release-readiness.yml: tools-catalog --check unwired");
  }

  if (misses.length === 0) {
    return {
      rId: "R100",
      requirement: REQUIREMENT,
      status: "pass",
      evidence: ["all 8 probes hit: stack present, README generated, pre-commit + CI wired"],
    };
  }
  return {
    rId: "R100",
    requirement: REQUIREMENT,
    status: "fail",
    evidence: [`${misses.length} probe(s) missed:`, ...misses.map((m) => `  ${m}`)],
    loc: join(root, "Tools"),
  };
}
