#!/usr/bin/env bun
/**
 * ConventionCache — Generates .sentinel/conventions.json from scan data
 *
 * Reads .sentinel/scan-report.json and optional inference output,
 * produces a JSON cache of enforceable conventions with regex patterns
 * for the fast Guard hook path (no inference, <2s checks).
 *
 * Usage: bun ConventionCache.ts [/path/to/repo]
 * Reads: .sentinel/scan-report.json, .sentinel/convention-report.json (if exists)
 * Writes: .sentinel/conventions.json
 */

import { existsSync, readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";

interface ConventionRule {
  id: string;
  category: string;
  pattern: string;
  /** Machine-readable rule summary. Never null — derived from regex, negative_regex,
   *  or the first 120 chars of natural-language pattern. Sentinel R17 enforces this. */
  rule: string;
  regex?: string;
  negative_regex?: string;
  applies_to: string[];
  scope: string;
  confidence: number;
}

interface ConventionCache {
  version: number;
  generated: string;
  project: string;
  conventions: ConventionRule[];
}

// Common convention-to-regex mappings.
// Keys are matched as case-insensitive substrings against `${conv.category} ${conv.pattern}`,
// so use distinctive phrases from real convention text (e.g. "banned multipliers", "bun for tools").
const REGEX_TEMPLATES: Record<string, { regex?: string; negative_regex?: string; applies_to: string[]; scope: string }> = {
  // Naming
  "camelCase for functions": {
    scope: "function_names",
    applies_to: ["*.ts", "*.tsx", "*.js", "*.jsx"],
  },
  "PascalCase for components": {
    scope: "component_names",
    applies_to: ["*.tsx", "*.jsx"],
  },

  // Imports
  "path alias for imports": {
    regex: "from ['\"]@/",
    negative_regex: "from ['\"]\\.\\.[\\/]\\.\\.[\\/]",
    applies_to: ["*.ts", "*.tsx"],
    scope: "import_statements",
  },
  "no deep relative imports": {
    negative_regex: "from ['\"]\\.\\.[\\/]\\.\\.[\\/]\\.\\.[\\/]",
    applies_to: ["*.ts", "*.tsx", "*.js", "*.jsx"],
    scope: "import_statements",
  },

  // Exports / files
  "barrel file exports": {
    regex: "export \\* from|export \\{[^}]+\\} from",
    applies_to: ["index.ts", "index.tsx"],
    scope: "exports",
  },
  "co-located test files": {
    scope: "test_organization",
    applies_to: ["*.test.ts", "*.test.tsx", "*.spec.ts"],
  },

  // Production hygiene
  "no console.log in production": {
    negative_regex: "(?<!//\\s)console\\.log\\(",
    applies_to: ["*.ts", "*.tsx"],
    scope: "production_logging",
  },

  // DOS-specific — banned voice / positioning
  "banned multipliers": {
    negative_regex: "\\b\\d+(?:\\.\\d+)?\\s*[xX×](?!\\w)",
    applies_to: ["*.md", "*.mdx", "*.ts", "*.tsx"],
    scope: "Positioning Vocabulary — Banned Multipliers",
  },
  "banned vocabulary": {
    negative_regex: "\\b\\d+(?:\\.\\d+)?\\s*[xX×](?!\\w)",
    applies_to: ["*.md", "*.mdx", "*.ts", "*.tsx"],
    scope: "Positioning Vocabulary",
  },

  // DOS-specific — Toolchain Runtime: bun shebang in Tools/
  "bun for tools": {
    negative_regex: "^#!/usr/bin/env node\\b",
    applies_to: ["*.ts"],
    scope: "Toolchain Runtime — bun for Tools/",
  },
  "toolchain runtime": {
    negative_regex: "^#!/usr/bin/env node\\b",
    applies_to: ["*.ts"],
    scope: "Toolchain Runtime — bun for Tools/",
  },

  // DOS-specific — Deployment: Railway not Vercel
  "railway not vercel": {
    negative_regex: "\"vercel\"|vercel\\.json|@vercel/",
    applies_to: ["package.json", "*.yml", "*.yaml"],
    scope: "Deployment — Railway not Vercel",
  },

  // DOS-specific — Inference wrapper: never import @anthropic-ai/sdk directly
  "inference wrapper": {
    negative_regex: "from ['\"]@anthropic-ai/sdk['\"]",
    applies_to: ["*.ts", "*.tsx"],
    scope: "DOS Inference Tool",
  },
  "anthropic sdk": {
    negative_regex: "from ['\"]@anthropic-ai/sdk['\"]",
    applies_to: ["*.ts", "*.tsx"],
    scope: "DOS Inference Tool",
  },
};

/** The note string the pre-2026-07-07 cache wrote into health.json alongside its
 *  hardcoded score:100. Detecting it lets the refresh strip that legacy clobber
 *  artifact (self-healing) while preserving genuinely measured scores. Exported
 *  so the test asserts against the same constant (no string drift). */
export const LEGACY_CACHE_NOTE_MARKER = "Regenerated by ConventionCache.ts";

/** Derives a non-null rule summary from whatever enforcement data is available. */
function deriveRule(
  negRegex: string | undefined,
  rx: string | undefined,
  pattern: string,
): string {
  if (negRegex) return `negative_regex:/${negRegex}/`;
  if (rx) return `regex:/${rx}/`;
  return pattern.slice(0, 120);
}

function printHelp(): void {
  console.log(`ConventionCache — Generate enforceable convention rules from scan data

USAGE
  bun ConventionCache.ts [options] [/path/to/repo]

ARGUMENTS
  /path/to/repo    Repository root with .sentinel/ data (default: current directory)

OPTIONS
  --help           Show this help message

PREREQUISITES
  Requires .sentinel/scan-report.json (run SentinelScan first)
  Optionally reads .sentinel/convention-report.json (from inference phase)

OUTPUT
  .sentinel/conventions.json — regex-based rules for fast Guard checks`);
  process.exit(0);
}

function main() {
  if (process.argv.includes("--help") || process.argv.includes("-h")) {
    printHelp();
  }

  const root = resolve(process.argv[2] || ".");
  const sentinelDir = join(root, ".sentinel");
  const scanReportPath = join(sentinelDir, "scan-report.json");
  const conventionReportPath = join(sentinelDir, "convention-report.json");

  if (!existsSync(scanReportPath)) {
    console.error("Error: .sentinel/scan-report.json not found. Run `sentinel scan` first.");
    process.exit(1);
  }

  const scanReport = JSON.parse(readFileSync(scanReportPath, "utf-8"));
  const projectName = scanReport.project?.name || "unknown";

  const rules: ConventionRule[] = [];

  // If inference-based convention report exists, use it
  if (existsSync(conventionReportPath)) {
    const conventionReport = JSON.parse(readFileSync(conventionReportPath, "utf-8"));
    const conventions = conventionReport.conventions || [];

    for (const conv of conventions) {
      if (!conv.enforceable || conv.confidence < 0.7) continue;

      // Inference-provided regex takes precedence over template lookup.
      // Future Phase-2 inference output may carry regex/negative_regex/applies_to directly.
      const inferenceRegex = typeof conv.regex === "string" ? conv.regex : undefined;
      const inferenceNegRegex = typeof conv.negative_regex === "string" ? conv.negative_regex : undefined;
      const inferenceAppliesTo = Array.isArray(conv.applies_to) ? conv.applies_to as string[] : undefined;

      // Match templates against category + pattern combined, since DOS conventions
      // often encode the rule in the category text (e.g. "Toolchain Runtime — bun for Tools/").
      const haystack = `${conv.category ?? ""} ${conv.pattern ?? ""}`.toLowerCase();
      const templateEntry = Object.entries(REGEX_TEMPLATES).find(([key]) =>
        haystack.includes(key.toLowerCase())
      );
      const template = templateEntry?.[1];

      const resolvedNegRx = inferenceNegRegex ?? template?.negative_regex;
      const resolvedRx = inferenceRegex ?? template?.regex;
      rules.push({
        id: `${conv.category}-${rules.length + 1}`,
        category: conv.category,
        pattern: conv.pattern,
        rule: deriveRule(resolvedNegRx, resolvedRx, conv.pattern),
        regex: resolvedRx,
        negative_regex: resolvedNegRx,
        applies_to: inferenceAppliesTo ?? template?.applies_to ?? ["*.ts", "*.tsx"],
        scope: template?.scope ?? conv.category,
        confidence: conv.confidence,
      });
    }
  }

  // Add rules derived from static analysis (always available)
  if (scanReport.existing?.hasEslint) {
    rules.push({
      id: "tooling-eslint",
      category: "tooling",
      pattern: "ESLint is configured — lint before committing",
      rule: "ESLint is configured — lint before committing",
      applies_to: ["*.ts", "*.tsx", "*.js", "*.jsx"],
      scope: "tooling",
      confidence: 1.0,
    });
  }

  if (scanReport.existing?.hasPrettier) {
    rules.push({
      id: "tooling-prettier",
      category: "tooling",
      pattern: "Prettier is configured — format before committing",
      rule: "Prettier is configured — format before committing",
      applies_to: ["*.ts", "*.tsx", "*.js", "*.jsx", "*.css", "*.json"],
      scope: "tooling",
      confidence: 1.0,
    });
  }

  if (scanReport.stack?.language === "TypeScript") {
    const tsNegRx = "\\.js$";
    rules.push({
      id: "language-typescript",
      category: "language",
      pattern: "Project uses TypeScript — avoid .js files for new code",
      rule: deriveRule(tsNegRx, undefined, "Project uses TypeScript — avoid .js files for new code"),
      negative_regex: tsNegRx,
      applies_to: ["*.js"],
      scope: "file_extension",
      confidence: 0.9,
    });
  }

  // Always add the memory-backup health convention (D3 — Safety operational hygiene).
  // Enforced by Sentinel R18. This convention surfaces in conventions.json so the
  // Guard warns when settings.json is edited without MemoryBackup wired.
  rules.push({
    id: "backup-health-1",
    category: "Safety — Memory Backup Present",
    pattern:
      "MemoryBackup.hook.ts must be registered in the settings.json SessionEnd group. " +
      "Last backup must be within 48 hours. Verified by Sentinel R18.",
    rule: "hook:MemoryBackup registered in settings.json SessionEnd + last backup <48h (Sentinel R18)",
    applies_to: ["settings.json"],
    scope: "Safety — Memory Backup Present",
    confidence: 1.0,
  });

  const generatedAt = new Date().toISOString();

  const cache: ConventionCache = {
    version: 1,
    generated: generatedAt,
    project: projectName,
    conventions: rules,
  };

  // writeArtifact:exempt — .sentinel/ conventions cache (path via var)
  writeFileSync(join(sentinelDir, "conventions.json"), JSON.stringify(cache, null, 2));
  console.log(`Convention cache generated: ${rules.length} rules for project "${projectName}"`);

  // D2 (amended 2026-07-07, Feathers council ruling): the cache refresh updates
  // FRESHNESS fields only — this tool must never author a health score. The
  // score is owned exclusively by the measured live-conformance sweep (Scan.md
  // Phase 2b-iv → `SentinelScan.ts sweep-conventions` + agent judgment sweep).
  // The prior behavior hardcoded score:100 here, which clobbered measured
  // scores on every cache refresh (studio's corrected 87% was overwritten
  // 2026-07-07). Measured fields in an existing health.json survive verbatim;
  // a legacy cache-authored score:100 artifact is stripped (self-healing);
  // absent any measurement, method is "unmeasured" and no score is written.
  const enforceableCount = rules.filter((r) => r.regex || r.negative_regex).length;
  const healthPath = join(sentinelDir, "health.json");
  let prior: Record<string, unknown> = {};
  if (existsSync(healthPath)) {
    // Guard non-object JSON too (`null`, `[]`, `"x"` parse fine but would crash the
    // note check or spread index-keyed junk) — anything but a plain object resets.
    try {
      const parsed: unknown = JSON.parse(readFileSync(healthPath, "utf-8"));
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) prior = parsed as Record<string, unknown>;
    } catch { prior = {}; }
  }
  const priorWasCacheAuthored = typeof prior.note === "string" && prior.note.includes(LEGACY_CACHE_NOTE_MARKER);
  if (priorWasCacheAuthored) {
    delete prior.score;
    delete prior.healthy_conventions;
    delete prior.drifting_conventions;
    delete prior.note;
    // The legacy `generated` was cache-authored too — leaving it would let a stale
    // cache timestamp masquerade as measurement recency (MineReflections' substrate
    // staleness gate reads health.json `generated`). `generated` belongs to the
    // measured sweep alone; this refresh's own timestamp is cache_generated.
    delete prior.generated;
  }
  const health = {
    ...prior,
    method: prior.method ?? (prior.score !== undefined ? "legacy-scan" : "unmeasured"),
    // total_conventions is the MEASURED denominator (score = healthy/total) — never
    // overwrite it when a measurement exists (the cache's rule count can differ from
    // the tracked-convention count, e.g. studio: 17 cached rules vs 23 tracked).
    // The cache's own count ships as cache_rules.
    total_conventions: prior.total_conventions ?? rules.length,
    cache_rules: rules.length,
    enforceable_conventions: enforceableCount,
    cache_generated: generatedAt,
    _generated_at: generatedAt,
    cache_note: "Convention cache refreshed by ConventionCache.ts — score fields are owned by the measured sweep (sentinel scan Phase 2b-iv), never this tool.",
  };
  // writeArtifact:exempt — .sentinel/ health cache (path via var)
  writeFileSync(healthPath, JSON.stringify(health, null, 2));
  console.log(
    `Health freshness updated: method=${health.method}, score=${(health as Record<string, unknown>).score ?? "(none — unmeasured)"}, total=${rules.length}, enforceable=${enforceableCount}`,
  );

  console.log(JSON.stringify(cache, null, 2));
}

// Guard: run the CLI only when invoked directly, so test/tool imports don't
// trigger a full cache regeneration (or process.exit) as an import side effect.
// Mirrors every sibling Sentinel tool (SentinelScan/Guard/Bootstrap/Status).
if (import.meta.main) main();
